repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.5
    hooks:
      - id: ruff-check
        args: [--fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^(tests/resources/|LICENSE$|\.gitignore$)
      - id: trailing-whitespace
        exclude: ^(tests/resources/|LICENSE$|\.gitignore$)
