language: python

python:
  - "2.7"
  - "3.7"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install unicodecsv; fi
  - pip install python-dateutil
  - pip install coverage
  - pip install coveralls
  - pip install .

script: pytest

after_success:
  - coverage run --source=procmon_parser/ -m pytest .
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
